services:
  ansible-libvirt:
      container_name: ansible-libvirt
      image:  ghcr.io/mcbtaguiad/libvirt-cloudinit-ansible:v1.0.0
      build:
          context: .
          dockerfile: ./docker/Dockerfile
      # entrypoint: tail -f /dev/null
      restart: always
      volumes:
      - "./:/ansible"
      - "~/.ssh/:/root/.ssh"
